name: Build, Check

on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

concurrency:
  # New commit on master branch cancels currently running workflows of this branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish_api_docs:
    uses: ./.github/workflows/publish_api_docs.yml