name: Publish API Documentation

on: [ workflow_dispatch, workflow_call ]

jobs: 
  api-doc:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Generating and publish autodocs
      run:  bash ./publish_api_docs.sh
